# Generated by Django 4.0.3 on 2022-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_featured_image_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='/static/images/default.jpg', null=True, upload_to=''),
        ),
    ]
